### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by davelab6** [googlefonts/typography#103]
:)

**Comment by jpamental** [comment]
Hoping for more input on what actually needs to be there @davelab6 ! Should there be links to privacy statement, etc? (and if so, where should they point?)

**Comment by kennethormandy** [comment]
<img width="1440" alt="Screenshot 2020-02-20 13 43 14" src="https://user-images.githubusercontent.com/1581276/74981507-3f228880-53e7-11ea-8062-8d088836589a.png">

<img width="525" alt="Screenshot 2020-02-20 13 44 12" src="https://user-images.githubusercontent.com/1581276/74981511-4053b580-53e7-11ea-867d-9c7e12a218c5.png">
