### ISSUE TITLE
Additional 3rd party content

### ISSUE THREAD

**Issue by davelab6** [googlefonts/typography#84]
I have a bunch of links to triage for inclusion in the "further reading" section; for now I'll drop a few here and continue to do so when I have a moment :)

https://css-tricks.com/one-file-many-options-using-variable-fonts-web/

https://css-tricks.com/typography-for-developers/

https://www.userzoom.com/blog/what-are-variable-fonts-and-how-do-they-benefit-ux/

https://medium.com/dev-channel/variable-fonts-and-the-digital-revolution-9b31cb910d7c

https://www.bbc.co.uk/rd/blog/2018-08-variable-fonts-open-type

https://www.shopify.com/partners/blog/variable-fonts

https://theblog.adobe.com/can-variable-fonts-illustrator-cc/

https://blogs.adobe.com/creative/adobe-indesign-2020/

https://blog.sketchapp.com/variable-fonts-improved-opentype-support-and-a-new-data-plugin-whats-new-in-sketch-e16f81bf8b75

https://create.adobe.com/2018/5/22/variable_fonts_are_t.html

https://www.nngroup.com/articles/variable-fonts-wide-screen-layout/

https://typetura.scottkellum.com/

**Comment by litherland** [comment]
Thanks, Dave! Note that we already opened [issue #6](https://github.com/googlefonts/typography/issues/6) to track resources—maybe it’s best to keep everything consolidated there? The issue links to a [gdoc](https://docs.google.com/document/d/1s3XCZTHvo157msE0oGw3hpgrMiwh7A9V0KkTt-hiMxI/edit?usp=sharing) where we started harvesting resources; Jason also added some to the site directly. Except for the last two (wasn’t sure if you were alluding to the [Nielson Norman piece](https://www.nngroup.com/articles/variable-fonts-wide-screen-layout/), and I couldn’t immediately locate the Typetura articles), I’ve dropped the resources you mention above into the gdoc. Feel free to add more there! I think I’ll wait until we’ve finalized triage to write/edit more descriptions.

**Comment by davelab6** [comment]
Yep that's the NN piece I was thinking of! I've updated the list, put it into the gdoc, and therefore closing this issue as I'll add additional stuff in the doc or #6 :)
